services:
  db-master:
    image: "${DB_IMAGE}"
    restart: always
    env_file:
      - ./conf/db.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/main.js:/main.js:ro
      - ./conf/master.cnf:/etc/mysql/conf.d/master.cnf:ro
      - ${DATA_PATH}/master:/var/lib/mysql
    command: ["deno","run","-A","main.js"]
  db-backup:
    image: "${DB_IMAGE}"
    restart: always
    env_file:
      - ./conf/db.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf/main.js:/main.js:ro
      - ./conf/slave.cnf:/etc/mysql/conf.d/slave.cnf:ro
      - ${DATA_PATH}/backup:/var/lib/mysql
    command: ["deno","run","-A","main.js","slave","-m=db-master","--id=100","-b=0 1 * * *"]